### ISSUE TITLE
Update to 1.16.0

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/python-ecmwf_grib-feedstock#7]
I updated `ecmwf_grib` in https://github.com/conda-forge/ecmwf_grib-feedstock/pull/15, but I believe it will be hard to refresh the patches for the `python-ecmwf_grib` (and I am not sure it is worth it). What o you think @kmuehlbauer?

**Comment by kmuehlbauer** [comment]
@ocefpaf 

Regarding the py3k-patch, this was a pure hack and I've come to the conclusion that this should be incorporated upstream. I already discussed with ecmwf-devs how we/I can try to bring py3k to `gribapi` as well as `eccodes`, but didn't had the time so far to finalize access to ecmwf-code base. So this is still on the plate. So, I'm sure dropping py3k-patch here is OK.

**Comment by ocefpaf** [comment]
> So, I'm sure dropping py3k-patch here is OK.

You mean skipping `py3k` while we wait for this to be upstream?

If so I tried very quickly and it failed the import. There are probably other changes too. I will revisite this in the future if you don't beat me to it :wink:

**Comment by kmuehlbauer** [comment]
Yes skipping `py3k`.

**Comment by kynan** [comment]
There will be no Python 3 support for grib_api since the library has been deprecated in favour of ecCodes. Python 3 support for ecCodes is being worked on.

**Comment by kynan** [comment]
What are your thoughts on updating to 1.19.0 and dropping Python 3 support? Happy to prepare a pull request.

**Comment by kmuehlbauer** [comment]
+1 for update from my side

**Comment by kynan** [comment]
OK. I'll wait until conda-forge/ecmwf_grib-feedstock#21 is in and then send a pr.

**Comment by kynan** [comment]
Done and merged! #14
